FROM ubuntu:18.10

MAINTAINER Mohammed Yehia <firefoxegy@gmail.com>

# update the system
RUN apt-get update --fix-missing

# install common packages
RUN apt-get install -y nano wget curl vim zip unzip git software-properties-common locales

# locales to UTF8
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update --fix-missing
RUN apt-get install -y python3-minimal python3-pip python3-setuptools
RUN apt-get install -y python3-dev default-libmysqlclient-dev
RUN pip3 install mysqlclient
RUN pip3 install django

# Cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 8000

COPY startpy.sh .
WORKDIR .
RUN chmod +x startpy.sh
ENTRYPOINT ["/startpy.sh"]
